spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://dpg-d06p819r0fns73fs2lbg-a.frankfurt-postgres.render.com:5432/hackaton_u8ka
    driver-class-name: org.postgresql.Driver
    username: hackaton_user
    password: qRwXpuWOcRDNB0HCiJnGjNfHQFygcTeO

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

